### ISSUE TITLE
utils/data/datasets/coco.py  has_valid_annotation  always return false?

### ISSUE THREAD

**Issue by jiawenhao2015** [soeaver/RP-R-CNN#7]
https://github.com/soeaver/RP-R-CNN/blob/dfcc227723d4bf6566356cda4513a84ed9a8ba30/utils/data/datasets/coco.py#L21-L35

**Comment by hugoycj** [comment]
> https://github.com/soeaver/RP-R-CNN/blob/dfcc227723d4bf6566356cda4513a84ed9a8ba30/utils/data/datasets/coco.py#L21-L35

I also met this problem. Wonder how you solve that. Thanks so much!!!

**Comment by jiawenhao2015** [comment]
> > https://github.com/soeaver/RP-R-CNN/blob/dfcc227723d4bf6566356cda4513a84ed9a8ba30/utils/data/datasets/coco.py#L21-L35
> 
> I also met this problem. Wonder how you solve that. Thanks so much!!!

just change Line 35， return True .....
